export const weekdays = [
  "sunday",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sun",
  "mon",
  "tue",
  "wed",
  "thu",
  "fri",
  "sat",
  "su",
  "mo",
  "tu",
  "we",
  "th",
  "fr",
  "sa",
];

export const months = [
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
  "jan",
  "feb",
  "mar",
  "apr",
  "may",
  "jun",
  "jul",
  "aug",
  "sep",
  "oct",
  "nov",
  "dec",
];

export type DurationCat = "minutes" | "hours" | "days" | "weeks" | "months" | "years";

export const durationCatMap: Record<string, DurationCat> = {
  minutes: "minutes",
  mins: "minutes",
  minute: "minutes",
  min: "minutes",
  hours: "hours",
  hrs: "hours",
  hour: "hours",
  hr: "hours",
  days: "days",
  day: "days",
  d: "days",
  weeks: "weeks",
  wks: "weeks",
  week: "weeks",
  wk: "weeks",
  months: "months",
  mnths: "months",
  month: "months",
  years: "years",
  yrs: "years",
  year: "years",
} as const;

export const durationCategories = Object.keys(durationCatMap);
